### ISSUE TITLE
Make the playlist image on the landing page the acutal ones

### ISSUE THREAD

**Issue by XelaG** [XelaG/Spotify-Stats-React-App#4]
Right now, the pictures on the landing page are always the same, in the spotify API there is an endpoint to get a playlist cover with it's id.

Could be cool to implement it 😄 

Here is the doc [link](https://developer.spotify.com/documentation/web-api/reference-beta/#endpoint-get-playlist-cover)

**Comment by alexgaignard** [comment]
This endpoint requires oauth auth, don't know why but this can't be done because of it 😢
